FROM trinodb/trino:421

ADD --chown=trino:trino https://packages.confluent.io/maven/io/confluent/kafka-protobuf-provider/7.3.1/kafka-protobuf-provider-7.3.1.jar /usr/lib/trino/plugin/kafka/
ADD --chown=trino:trino https://packages.confluent.io/maven/io/confluent/kafka-protobuf-types/7.3.1/kafka-protobuf-types-7.3.1.jar /usr/lib/trino/plugin/kafka/
